import { CalendarDays, Database, DoorOpen, Mail, MapPin, MessageSquare, Phone, RefreshCw, ShieldAlert, Target, TrendingUp, UserCheck, Users } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";

type D={generatedAt:string;metrics:any;wards:any[];recentImports:any[];availability:any};
const num=(v:any)=>Number(v??0).toLocaleString("en-KE");
const pct=(v:any)=>`${Math.max(0,Math.min(100,Number(v??0)))}%`;
const when=(v:any)=>{if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?"—":d.toLocaleString("en-KE",{dateStyle:"short",timeStyle:"short"})};
async function loadData(){const r=await fetch("/api/dashboard-intelligence/overview",{credentials:"include"});const t=await r.text();const d=t?JSON.parse(t):null;if(!r.ok)throw new Error(d?.error??`Request failed (${r.status})`);return d as D}
function Card({label,value,note,Icon,off=false}:{label:string;value:any;note:string;Icon:any;off?:boolean}){return <article className="border border-border bg-card p-4"><div className="flex items-start justify-between"><p className="font-mono text-[9px] text-muted-foreground">{label}</p><Icon className={`h-4 w-4 ${off?"text-muted-foreground":"text-primary"}`}/></div><p className="mt-3 font-mono text-2xl">{value}</p><p className="mt-1 font-mono text-[8px] text-muted-foreground">{off?"NO_ACTIVITY_YET":note}</p></article>}
export default function LiveDashboardV9A(){
 const [d,setD]=useState<D|null>(null),[err,setErr]=useState<string|null>(null),[busy,setBusy]=useState(true);
 const load=useCallback(async()=>{setBusy(true);setErr(null);try{setD(await loadData())}catch(e){setErr(e instanceof Error?e.message:"Unable to load dashboard")}finally{setBusy(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const m=d?.metrics??{}; const maxWard=useMemo(()=>Math.max(1,...(d?.wards??[]).map(w=>Number(w.constituents??0))),[d?.wards]);
 return <div className="space-y-4 p-4 lg:p-6">
  <section className="flex flex-col gap-3 border border-border bg-card p-4 lg:flex-row lg:items-start lg:justify-between"><div><p className="font-mono text-[10px] tracking-widest text-primary">PHASE 9A LIVE DASHBOARD INTELLIGENCE</p><h1 className="mt-1 text-xl font-semibold">Command Overview</h1><p className="mt-1 text-xs text-muted-foreground">Live constituent, operational and readiness metrics.</p></div><div className="flex flex-wrap gap-2"><span className="border border-green-400/30 px-3 py-2 font-mono text-[9px] text-green-400">LIVE DATA</span><span className="border border-border px-3 py-2 font-mono text-[9px]">{d?when(d.generatedAt):"AWAITING DATA"}</span><button onClick={()=>void load()} className="flex items-center gap-1 border border-border px-3 py-2 font-mono text-[9px]"><RefreshCw className={`h-3 w-3 ${busy?"animate-spin":""}`}/>REFRESH</button></div></section>
  {err&&<div className="border border-red-400/30 bg-red-400/10 p-3 font-mono text-xs text-red-400">{err}</div>}
  <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
   <Card label="TOTAL CONSTITUENTS" value={num(m.totalConstituents)} note="MASTER IDENTITY GRAPH" Icon={Users}/><Card label="PHONE READY" value={num(m.phoneReady)} note="DIRECT CONTACT COVERAGE" Icon={Phone}/><Card label="WARDS COVERED" value={num(m.wardsCovered)} note={`${num(m.constituenciesCovered)} CONSTITUENCIES`} Icon={MapPin}/><Card label="OPEN THREATS" value={num(m.openThreats)} note="NARRATIVE INTELLIGENCE" Icon={ShieldAlert} off={!d?.availability.intelligence}/>
   <Card label="ACTIVE VOLUNTEERS" value={num(m.activeVolunteers)} note="FIELD FORCE" Icon={UserCheck} off={!d?.availability.volunteers}/><Card label="MESSAGES SENT" value={num(m.messagesSent)} note="ALL CHANNELS" Icon={MessageSquare} off={!d?.availability.messaging}/><Card label="DOORS KNOCKED" value={num(m.doorsKnocked)} note="FIELD OPERATIONS" Icon={DoorOpen} off={!d?.availability.fieldOperations}/><Card label="UPCOMING EVENTS" value={num(m.upcomingEvents)} note="SCHEDULED" Icon={CalendarDays} off={!d?.availability.events}/>
  </section>
  <section className="grid gap-4 xl:grid-cols-[1.25fr_0.75fr]"><div className="border border-border bg-card p-4"><div className="flex items-center justify-between"><div><p className="font-mono text-[10px]">CONSTITUENT INTELLIGENCE</p><p className="mt-1 text-xs text-muted-foreground">Demographic, contact and geographic coverage.</p></div><Database className="h-4 w-4 text-primary"/></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["WOMEN",m.women,Users],["MEN",m.men,Users],["YOUTH 18–35",m.youth,TrendingUp],["SENIORS 60+",m.seniors,Users],["EMAIL READY",m.emailReady,Mail],["SMS CONSENT",m.smsConsented,MessageSquare],["WHATSAPP",m.whatsappConsented,MessageSquare],["POLLING STATIONS",m.pollingStations,MapPin]].map(([l,v,I]:any)=><div key={l} className="border border-border p-3"><div className="flex items-center justify-between"><p className="font-mono text-[8px] text-muted-foreground">{l}</p><I className="h-3 w-3 text-primary"/></div><p className="mt-2 font-mono text-lg">{num(v)}</p></div>)}</div></div><div className="border border-border bg-card p-4"><p className="font-mono text-[10px]">READINESS SCORES</p>{[["DATA READINESS",m.dataReadiness,"Phone and ward completeness"],["OPERATIONAL READINESS",m.operationalReadiness,"Database, field force, communications and events"]].map(([l,v,note]:any)=><div key={l} className="mt-4"><div className="flex items-center justify-between"><p className="font-mono text-[9px]">{l}</p><p className="font-mono text-lg">{pct(v)}</p></div><div className="mt-2 h-2 bg-secondary"><div className="h-full bg-primary" style={{width:pct(v)}}/></div><p className="mt-2 text-[10px] text-muted-foreground">{note}</p></div>)}</div></section>
  <section className="grid gap-4 xl:grid-cols-[1.25fr_0.75fr]"><div className="border border-border bg-card p-4"><div className="flex items-center justify-between"><div><p className="font-mono text-[10px]">TOP WARDS BY DATABASE COVERAGE</p><p className="mt-1 text-xs text-muted-foreground">Based on imported campaign identities.</p></div><MapPin className="h-4 w-4 text-primary"/></div><div className="mt-4 space-y-3">{(d?.wards??[]).map(w=><div key={w.ward}><div className="flex items-center justify-between"><div><p className="font-mono text-[10px]">{w.ward}</p><p className="mt-1 font-mono text-[8px] text-muted-foreground">{num(w.phone_ready)} PHONE READY · {num(w.women)} WOMEN</p></div><p className="font-mono text-sm">{num(w.constituents)}</p></div><div className="mt-2 h-1.5 bg-secondary"><div className="h-full bg-primary" style={{width:`${Math.max(2,Math.round(Number(w.constituents??0)/maxWard*100))}%`}}/></div></div>)}</div></div><div className="border border-border bg-card p-4"><div className="flex items-center justify-between"><p className="font-mono text-[10px]">SUPPORT CLASSIFICATION</p><Target className="h-4 w-4 text-primary"/></div><div className="mt-4 space-y-2">{[["STRONG",m.strongSupport],["LEANING",m.leaningSupport],["UNDECIDED",m.undecided],["OPPOSED",m.opposed]].map(([l,v]:any)=><div key={l} className="flex items-center justify-between border border-border p-3"><p className="font-mono text-[9px]">{l}</p><p className="font-mono text-lg">{num(v)}</p></div>)}</div><div className="mt-4 border border-border bg-secondary/20 p-3"><p className="font-mono text-[8px] text-muted-foreground">DATA QUALITY</p><p className="mt-2 text-xs">Missing phones: {num(m.missingPhone)}</p><p className="mt-1 text-xs">Missing wards: {num(m.missingWard)}</p></div></div></section>
  <section className="border border-border bg-card"><header className="border-b border-border p-4"><p className="font-mono text-[10px]">RECENT DATA OPERATIONS</p><p className="mt-1 text-xs text-muted-foreground">Latest campaign import activity.</p></header><div className="divide-y divide-border">{(d?.recentImports??[]).map(j=><div key={j.id} className="grid gap-3 p-4 md:grid-cols-[1fr_repeat(4,120px)]"><div><p className="text-xs font-medium">{j.file_name}</p><p className="mt-1 font-mono text-[8px] text-muted-foreground">{String(j.status).toUpperCase()} · {when(j.completed_at??j.created_at)}</p></div>{[["READ",j.total_rows],["IMPORTED",j.imported_rows],["UPDATED",j.updated_rows],["DUPLICATES",j.duplicate_rows]].map(([l,v]:any)=><div key={l}><p className="font-mono text-[8px] text-muted-foreground">{l}</p><p className="mt-1 font-mono text-sm">{num(v)}</p></div>)}</div>)}</div></section>
 </div>
}
