import { Router, type IRouter } from "express";
import healthRouter from "./health";
import dashboardRouter from "./dashboard";
import membersRouter from "./members";
import segmentsRouter from "./segments";
import messagingRouter from "./messaging";
import fieldOpsRouter from "./field-ops";
import volunteersRouter from "./volunteers";
import surveysRouter from "./surveys";
import eventsRouter from "./events";
import intelligenceRouter from "./intelligence";
import campaignPlanRouter from "./campaign-plan";
import kolRouter from "./kol";
import fundraisingRouter from "./fundraising";
import mpesaRouter from "./mpesa";
import electionDayRouter from "./election-day";
import turnoutRouter from "./turnout";
import voterRegistryRouter from "./voter-registry";
import credentialsRouter from "./credentials";
import adminRouter from "./admin";
import analyticsRouter from "./analytics";
import insightsRouter from "./insights";
import aiRouter from "./ai";
import speechesRouter from "./speeches";
import socialRouter from "./social";
import diRouter from "./di";
import strategistRouter from "./strategist";
import authRouter from "./auth";
import electionWarRoomRouter from "./election-war-room";
import productionReadinessRouter from "./production-readiness";
import gisIntelligenceRouter from "./gis-intelligence";
import finalReleaseRouter from "./final-release";
import smartAssistRouter from "./smart-assist";
import approvalsRouter from "./approvals";
import contactsRouter from "./contacts";
import integrationsRouter from "./integrations";
import geographyRouter from "./geography";
import documentsRouter from "./documents";
import commandCentreRouter from "./command-centre";
import campaignDatabaseRouter from "./campaign-database";
import dataImportRouter from "./data-import";
import phase7OperationsRouter from "./phase7-operations";
import phase6HealthRouter from "./phase6-health";
import localIntelligenceRouter from "./local-intelligence";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/election-war-room", electionWarRoomRouter);
router.use("/production-readiness", productionReadinessRouter);
router.use("/gis-intelligence", gisIntelligenceRouter);
router.use("/final-release", finalReleaseRouter);
router.use("/smart-assist", smartAssistRouter);
router.use("/approvals", approvalsRouter);
router.use("/contacts", contactsRouter);
router.use("/integrations", integrationsRouter);
router.use("/geography", geographyRouter);
router.use("/documents", documentsRouter);
router.use("/command-centre", commandCentreRouter);
router.use("/campaign-database", campaignDatabaseRouter);
router.use("/data-import", dataImportRouter);
router.use("/phase7-operations", phase7OperationsRouter);
router.use("/phase6-health", phase6HealthRouter);
router.use("/local-intelligence", localIntelligenceRouter);
router.use("/dashboard", dashboardRouter);
router.use("/members", membersRouter);
router.use("/segments", segmentsRouter);
router.use("/messages", messagingRouter);
router.use("/field-ops", fieldOpsRouter);
router.use("/volunteers", volunteersRouter);
router.use("/surveys", surveysRouter);
router.use("/events", eventsRouter);
router.use("/intelligence", intelligenceRouter);
router.use("/campaign-plan", campaignPlanRouter);
router.use("/kol", kolRouter);
router.use("/fundraising/mpesa", mpesaRouter);
router.use("/fundraising", fundraisingRouter);
router.use("/election-day", electionDayRouter);
router.use("/turnout", turnoutRouter);
router.use("/voter-registry", voterRegistryRouter);
router.use("/credentials", credentialsRouter);
router.use("/admin", adminRouter);
router.use("/analytics", analyticsRouter);
router.use("/insights", insightsRouter);
router.use("/ai", aiRouter);
router.use("/speeches", speechesRouter);
router.use("/social", socialRouter);
router.use("/di", diRouter);
router.use("/strategist", strategistRouter);

export default router;
