import { Router } from "express";
import { z } from "zod";
import { desc, eq, ilike, or } from "drizzle-orm";
import { db, campaignContactsTable, contactImportBatchesTable } from "@workspace/db";
import { requireAuth, requireActionPermission, enforceGeographicScope } from "../lib/auth";
import { MAKUENI_CONSTITUENCIES, MAKUENI_WARDS } from "../lib/geography";
const router=Router(); router.use(requireAuth,requireActionPermission("contacts","view","read"),enforceGeographicScope());
function phone(v:string){let d=v.replace(/\D/g,""); if(d.startsWith("0"))d="254"+d.slice(1); if(d.startsWith("7")||d.startsWith("1"))d="254"+d; return /^254[17]\d{8}$/.test(d)?`+${d}`:null;}
const rowSchema=z.object({name:z.string().min(1),phone:z.string().min(1),email:z.string().optional(),constituency:z.string().optional(),ward:z.string().optional(),pollingCentre:z.string().optional(),pollingStation:z.string().optional(),village:z.string().optional(),consentStatus:z.string().optional()});
router.get("/",async(req,res)=>{const q=String(req.query.q??"").trim(); const rows=q?await db.select().from(campaignContactsTable).where(or(ilike(campaignContactsTable.fullName,`%${q}%`),ilike(campaignContactsTable.normalizedPhone,`%${q}%`))).orderBy(desc(campaignContactsTable.createdAt)).limit(500):await db.select().from(campaignContactsTable).orderBy(desc(campaignContactsTable.createdAt)).limit(500);res.json(rows)});
router.post("/import",requireActionPermission("contacts","import"),async(req,res)=>{const rows=Array.isArray(req.body?.rows)?req.body.rows:[]; const u=req.currentUser!; const [batch]=await db.insert(contactImportBatchesTable).values({filename:String(req.body?.filename??"contacts.json"),importedById:u.id,totalRows:rows.length}).returning(); let accepted=0,duplicates=0,invalid=0; const errors:any[]=[]; for(let i=0;i<rows.length;i++){const parsed=rowSchema.safeParse(rows[i]); if(!parsed.success){invalid++;errors.push({row:i+1,error:"Invalid required fields"});continue;} const r=parsed.data,p=phone(r.phone); if(!p){invalid++;errors.push({row:i+1,error:"Invalid Kenyan phone number"});continue;} if(r.constituency&&!MAKUENI_CONSTITUENCIES.includes(r.constituency)){invalid++;errors.push({row:i+1,error:"Unknown Makueni constituency"});continue;} if(r.ward&&!MAKUENI_WARDS.includes(r.ward)){invalid++;errors.push({row:i+1,error:"Unknown Makueni ward"});continue;} const exists=await db.select({id:campaignContactsTable.id}).from(campaignContactsTable).where(eq(campaignContactsTable.normalizedPhone,p)).limit(1); if(exists.length){duplicates++;continue;} await db.insert(campaignContactsTable).values({fullName:r.name,normalizedPhone:p,originalPhone:r.phone,email:r.email,constituency:r.constituency,ward:r.ward,pollingCentre:r.pollingCentre,pollingStation:r.pollingStation,village:r.village,consentStatus:r.consentStatus??"unknown",importBatchId:batch.id});accepted++;} const [done]=await db.update(contactImportBatchesTable).set({status:"completed",acceptedRows:accepted,duplicateRows:duplicates,invalidRows:invalid,errorReport:errors,completedAt:new Date()}).where(eq(contactImportBatchesTable.id,batch.id)).returning();res.status(201).json(done)});
router.delete("/:id",requireActionPermission("contacts","delete"),async(req,res)=>{await db.update(campaignContactsTable).set({isActive:false,updatedAt:new Date()}).where(eq(campaignContactsTable.id,Number(req.params.id)));res.status(204).send()});
router.get("/imports/history",async(_req,res)=>res.json(await db.select().from(contactImportBatchesTable).orderBy(desc(contactImportBatchesTable.createdAt)).limit(100)));
export default router;
