import { AlertTriangle, CheckCircle2, Expand, Gauge, Layers3, MapPinned, Pause, Play, Radio, RefreshCw, ShieldAlert, Users, Vote, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
const BASE=import.meta.env.BASE_URL??"/";
const num=(v:any)=>Number(v??0).toLocaleString("en-KE");
const clamp=(v:number)=>Math.max(0,Math.min(100,v));
const rows=(p:any,k:string[])=>Array.isArray(p)?p:k.map(x=>p?.[x]).find(Array.isArray)??[];
export default function GisCentre(){
 const [wards,setWards]=useState<any[]>([]),[stations,setStations]=useState<any[]>([]),[selected,setSelected]=useState(""),[layer,setLayer]=useState("risk"),[auto,setAuto]=useState(true),[wall,setWall]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const [a,b,c]=await Promise.all([fetch(`${BASE}api/dashboard-intelligence/overview`,{credentials:"include"}),fetch(`${BASE}api/turnout/operations-centre/live-command`,{credentials:"include"}),fetch(`${BASE}api/election-day/stations`,{credentials:"include"})]);const [oa,t,p]=await Promise.all([a.ok?a.json():{},b.ok?b.json():{},c.ok?c.json():[]]);const ow=rows(oa,["wards"]),tw=rows(t,["wards"]),ss=rows(p,["stations"]);const tm=new Map(tw.map((x:any)=>[String(x.ward),x]));const sm=new Map<string,any[]>();for(const s of ss){const w=String(s.ward??"UNASSIGNED");sm.set(w,[...(sm.get(w)??[]),s]);}setWards(ow.map((x:any)=>{const w=String(x.ward??"UNASSIGNED"),y:any=tm.get(w),st=sm.get(w)??[],count=Number(y?.stations??st.length),opened=Number(y?.opened??0);return{ward:w,constituency:x.constituency??y?.constituency??null,registeredVoters:Number(y?.registered??0)||st.reduce((n:number,s:any)=>n+Number(s.registeredVoters??0),0),pollingStations:count,volunteers:Number(x.volunteers??y?.agentsPresent??0),turnout:Number(y?.turnoutRate??y?.turnout??0),reportingRate:Number(y?.reportingRate??(count?Math.round(opened/count*100):0)),incidents:Number(y?.activeIncidents??0),riskScore:Number(y?.riskScore??x.risk_score??x.riskScore??0),opportunityScore:Number(x.opportunity_score??x.opportunityScore??0)};}));setStations(ss);}catch(e){setError(e instanceof Error?e.message:"Unable to load GIS data");}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);useEffect(()=>{if(!auto)return;const i=setInterval(()=>void load(),30000);return()=>clearInterval(i);},[auto,load]);
 const current=wards.find(w=>w.ward===selected),selectedStations=stations.filter(s=>String(s.ward??"UNASSIGNED")===selected),county=useMemo(()=>({wards:wards.length,stations:wards.reduce((n,w)=>n+Number(w.pollingStations??0),0),registered:wards.reduce((n,w)=>n+Number(w.registeredVoters??0),0),incidents:wards.reduce((n,w)=>n+Number(w.incidents??0),0),volunteers:wards.reduce((n,w)=>n+Number(w.volunteers??0),0),risk:wards.length?Math.round(wards.reduce((n,w)=>n+Number(w.riskScore??0),0)/wards.length):0}),[wards]);
 const score=(w:any)=>layer==="turnout"?clamp(w.turnout):layer==="reporting"?clamp(w.reportingRate):layer==="volunteers"?clamp(Math.round(Number(w.volunteers??0)/Math.max(1,...wards.map(x=>Number(x.volunteers??0)))*100)):clamp(w.riskScore);
 return <div className={wall?"fixed inset-0 z-[100] overflow-y-auto bg-background p-3 sm:p-6":"mx-auto max-w-[2200px] space-y-4"}>
 <header className="flex flex-col gap-3 border border-border bg-card p-4 xl:flex-row xl:items-start xl:justify-between"><div><div className="flex items-center gap-2"><MapPinned className="h-5 w-5 text-primary"/><h1 className="text-lg font-bold tracking-widest sm:text-xl">LIVE GIS ELECTION COMMAND</h1></div><p className="mt-1 font-mono text-[9px] tracking-widest text-muted-foreground">WARDS · POLLING STATIONS · TURNOUT · INCIDENTS · VOLUNTEERS · REPORTING</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>setAuto(v=>!v)} className="flex min-h-10 items-center gap-2 border border-border px-3 py-2 font-mono text-[8px]">{auto?<Pause className="h-3 w-3"/>:<Play className="h-3 w-3"/>} AUTO {auto?"ON":"OFF"}</button><button onClick={()=>void load()} className="flex min-h-10 items-center gap-2 border border-border px-3 py-2 font-mono text-[8px]"><RefreshCw className={`h-3 w-3 ${loading?"animate-spin":""}`}/> REFRESH</button><button onClick={()=>setWall(v=>!v)} className="flex min-h-10 items-center gap-2 bg-primary px-3 py-2 font-mono text-[8px] text-primary-foreground">{wall?<X className="h-3 w-3"/>:<Expand className="h-3 w-3"/>}{wall?"EXIT WALL":"COMMAND WALL"}</button></div></header>
 {error&&<div className="border border-red-400/40 bg-red-400/5 p-3 text-xs text-red-400">{error}</div>}
 <div className="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-6">{[["WARDS",county.wards,MapPinned],["STATIONS",county.stations,Vote],["REGISTERED",county.registered,Users],["VOLUNTEERS",county.volunteers,Users],["INCIDENTS",county.incidents,AlertTriangle],["COUNTY RISK",`${county.risk}%`,Gauge]].map(([l,v,I]:any)=><article key={l} className="border border-border bg-card p-3 sm:p-4"><div className="flex items-center justify-between"><p className="font-mono text-[8px] text-muted-foreground">{l}</p><I className="h-4 w-4 text-primary"/></div><p className="mt-2 truncate font-mono text-lg">{typeof v==="number"?num(v):v}</p></article>)}</div>
 <section className="border border-border bg-card p-3 sm:p-4"><div className="flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between"><div><p className="font-mono text-[10px] tracking-widest">MAP LAYER</p><p className="mt-1 text-xs text-muted-foreground">Choose the metric used to colour the ward matrix.</p></div><div className="grid grid-cols-2 gap-2 sm:flex">{[["risk","RISK",ShieldAlert],["turnout","TURNOUT",Vote],["reporting","REPORTING",Radio],["volunteers","VOLUNTEERS",Users]].map(([v,l,I]:any)=><button key={v} onClick={()=>setLayer(v)} className={`flex min-h-10 items-center justify-center gap-2 border px-3 py-2 font-mono text-[8px] ${layer===v?"border-primary bg-primary text-primary-foreground":"border-border"}`}><I className="h-3 w-3"/>{l}</button>)}</div></div></section>
 <div className="grid grid-cols-1 gap-4 2xl:grid-cols-[1.35fr_0.65fr]"><section className="border border-border bg-card p-3 sm:p-4"><div className="flex items-center justify-between"><div><p className="font-mono text-[10px] tracking-widest">MAKUENI WARD SITUATION MAP</p><p className="mt-1 text-xs text-muted-foreground">Live ward-level geographic command matrix.</p></div><Layers3 className="h-4 w-4 text-primary"/></div><div className="mt-4 grid grid-cols-1 gap-2 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">{wards.map(w=><button key={w.ward} onClick={()=>setSelected(w.ward)} className={`border p-3 text-left ${selected===w.ward?"border-primary ring-1 ring-primary":"border-border hover:border-primary/60"}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-medium">{w.ward}</p><p className="mt-1 truncate font-mono text-[8px] text-muted-foreground">{w.constituency||"CONSTITUENCY NOT SET"}</p></div><span className="shrink-0 border border-border px-2 py-1 font-mono text-[8px]">{score(w)}%</span></div><div className="mt-3 h-1.5 bg-secondary"><div className="h-full bg-primary" style={{width:`${score(w)}%`}}/></div><div className="mt-3 grid grid-cols-2 gap-2 font-mono text-[7px] text-muted-foreground"><span>{num(w.registeredVoters)} REGISTERED</span><span>{num(w.pollingStations)} STATIONS</span><span>{num(w.volunteers)} VOLUNTEERS</span><span>{num(w.incidents)} INCIDENTS</span></div></button>)}</div>{!loading&&!wards.length&&<div className="mt-4 border border-dashed border-border py-12 text-center font-mono text-[10px] text-muted-foreground">[ NO_WARD_GIS_DATA_AVAILABLE ]</div>}</section>
 <aside className="space-y-4"><section className="border border-border bg-card p-4"><p className="font-mono text-[10px] tracking-widest">WARD INTELLIGENCE</p>{current?<div className="mt-4"><p className="text-lg font-semibold">{current.ward}</p><p className="font-mono text-[8px] text-muted-foreground">{current.constituency||"CONSTITUENCY NOT SET"}</p><div className="mt-3 grid grid-cols-2 gap-2">{[["REGISTERED",current.registeredVoters],["STATIONS",current.pollingStations],["TURNOUT",`${current.turnout}%`],["REPORTING",`${current.reportingRate}%`],["VOLUNTEERS",current.volunteers],["INCIDENTS",current.incidents],["RISK",`${current.riskScore}%`],["OPPORTUNITY",`${current.opportunityScore}%`]].map(([l,v])=><div key={String(l)} className="border border-border p-3"><p className="font-mono text-[7px] text-muted-foreground">{l}</p><p className="mt-2 font-mono text-sm">{typeof v==="number"?num(v):v}</p></div>)}</div></div>:<div className="mt-4 border border-dashed border-border py-10 text-center font-mono text-[9px] text-muted-foreground">SELECT A WARD</div>}</section><section className="border border-border bg-card p-4"><p className="font-mono text-[10px] tracking-widest">POLLING STATIONS</p><div className="mt-4 max-h-[460px] space-y-2 overflow-y-auto">{selectedStations.map(s=><div key={s.code??s.name} className="border border-border p-3"><p className="truncate text-xs font-medium">{s.name||s.code}</p><p className="mt-1 font-mono text-[7px] text-muted-foreground">{s.code||"NO CODE"} · {String(s.status??"pending").toUpperCase()}</p><p className="mt-2 font-mono text-[7px] text-muted-foreground">{num(s.registeredVoters)} REGISTERED · {s.agentName||"NO AGENT"}</p></div>)}</div></section></aside></div>
 <section className="grid grid-cols-1 gap-3 md:grid-cols-3">{[[CheckCircle2,"GPS READINESS","Ready for exact polling-station coordinates and GeoJSON boundaries."],[AlertTriangle,"INCIDENT LAYER","Ward-level incident counts are already included in risk."],[Radio,"LIVE OPERATIONS","Data refreshes automatically every 30 seconds."]].map(([I,t,d]:any)=><article key={t} className="border border-border bg-card p-4"><I className="h-4 w-4 text-primary"/><p className="mt-3 font-mono text-[9px] tracking-widest">{t}</p><p className="mt-2 text-xs text-muted-foreground">{d}</p></article>)}</section>
 </div>;
}
