import { FormEvent, useEffect, useState } from "react";
import { AlertTriangle, CheckCircle2, ClipboardList, MapPin, Plus, Users } from "lucide-react";
import { CAMPAIGN_UI } from "../config/campaign-ui";
import { CAMPAIGN_OPERATIONS } from "../config/campaign-operations";
const BASE=import.meta.env.BASE_URL;
async function api(path:string, init?:RequestInit){const r=await fetch(`${BASE}api/command-centre${path}`,{headers:{"Content-Type":"application/json"},...init});if(!r.ok)throw new Error(await r.text());return r.json();}
export default function OperationsHub(){
 const [tasks,setTasks]=useState<any[]>([]),[incidents,setIncidents]=useState<any[]>([]),[title,setTitle]=useState("");
 const load=async()=>{const [t,i]=await Promise.all([api('/tasks'),api('/incidents')]);setTasks(t);setIncidents(i)};useEffect(()=>{load()},[]);
 const add=async(e:FormEvent)=>{e.preventDefault();if(!title.trim())return;await api('/tasks',{method:'POST',body:JSON.stringify({title,category:'field',priority:'normal',status:'pending'})});setTitle('');load()};
 return <div className="space-y-5"><div><h1 className="text-xl font-bold tracking-widest">OPERATIONS HUB</h1><p className="font-mono text-[10px] text-muted-foreground">PHASE 4 · TASKS · INCIDENTS · DEPLOYMENTS · CHECK-INS</p></div>
 <form onSubmit={add} className="bg-card border border-border p-4 flex gap-2"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Create a field task..." className="flex-1 bg-background border border-border px-3 py-2 text-sm"/><button type="submit" className="bg-primary text-primary-foreground px-4 flex items-center gap-2 text-xs font-mono"><Plus className="w-4 h-4"/>ADD TASK</button></form>
 <div className="grid gap-4 lg:grid-cols-2"><section className="bg-card border border-border"><div className="p-4 border-b border-border flex gap-2 font-bold"><ClipboardList className="w-4 h-4 text-primary"/>FIELD TASKS</div><div className="divide-y divide-border">{tasks.slice(0,20).map(t=><div key={t.id} className="p-4 flex justify-between gap-3"><div><p className="font-medium">{t.title}</p><p className="text-xs text-muted-foreground">{t.ward||'County-wide'} · {t.assignedTo||'Unassigned'}</p></div><span className="text-[10px] font-mono border border-border px-2 py-1 h-fit">{t.status}</span></div>)}{!tasks.length&&<p className="p-6 text-sm text-muted-foreground">No tasks yet.</p>}</div></section>
 <section className="bg-card border border-border"><div className="p-4 border-b border-border flex gap-2 font-bold"><AlertTriangle className="w-4 h-4 text-primary"/>FIELD INCIDENTS</div><div className="divide-y divide-border">{incidents.slice(0,20).map(i=><div key={i.id} className="p-4"><div className="flex justify-between"><p className="font-medium">{i.title}</p><span className="text-[10px] font-mono">{i.severity}</span></div><p className="text-xs text-muted-foreground flex gap-1 mt-1"><MapPin className="w-3 h-3"/>{i.ward||'Location pending'} · {i.status}</p></div>)}{!incidents.length&&<p className="p-6 text-sm text-muted-foreground">No incidents reported.</p>}</div></section></div>
 <div className="grid gap-3 sm:grid-cols-3"><div className="border border-border bg-card p-4 flex gap-3"><Users className="text-primary"/><span>Volunteer deployment</span></div><div className="border border-border bg-card p-4 flex gap-3"><CheckCircle2 className="text-primary"/><span>GPS check-ins</span></div><div className="border border-border bg-card p-4 flex gap-3"><MapPin className="text-primary"/><span>Polling-station coverage</span></div></div></div>
}
